my_dbt_project:
  outputs:
    dev:
      account: EFYWQRI-QTB00212
      database: SNOWFLAKE_SAMPLE_DATA
      password: "{{env_var('SNOWFLAKE_PW')}}"
      role: ACCOUNTADMIN
      schema: INFORMATION_SCHEMA
      threads: 1
      type: snowflake
      user: MATTHEWKELLEHER
      warehouse: COMPUTE_WH
  target: dev
